training:
    data_home: "/home/fcf/projects/parallel_mlps/datasets/"
    n_splits: 10
    validation_rate_from_train: 0.25

    dataset: "diabetes"

    experiment_num: 0

    project_name: "novo_teste"
model:
    all_data_to_device: True
    loss_function: cross_entropy
    optimizer_cls: adam
    learning_rate: 1e-2 #3e-4
    num_epochs: 100
    batch_size: 32
    num_workers: 0
    repetitions: 10
    activations:
        - identity
        - relu
        - leakyrelu
        - selu
        # - elu
        - gelu
        - sigmoid
        - tanh
    min_neurons: 1
    max_neurons: 100
    max_layers: null
    step_neurons: 1
    local_patience: 20
    global_patience: 2
    transform_data_strategy: append_original_input
    loss_rel_tol: 0.01
    min_improvement: 0.001
    device: "cuda"

hydra:
    sweep:
        dir: outputs/${training.project_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${training.dataset}/${training.experiment_num}/
        subdir: ${training.experiment_num}
