training:
    data_home: "~/fcf/projects/parallel_mlps/datasets/"
    n_splits: 10
    validation_rate_from_train: 0.25
    debug_test: False

    dataset: "diabetes"

    experiment_num: 0

    num_epochs: 100
    batch_size: 32
    drop_samples: 0.1
    input_perturbation: sqrt #random_sparsity0.1 #sqrt

    project_name: "novo_teste"
model:
    all_data_to_device: True
    loss_function: cross_entropy
    optimizer_name: adam
    learning_rate: 3e-4
    num_workers: 0
    repetitions: 10
    repetitions_for_best_neuron: 100
    strategy_select_best: global_best #carchitecture_median_best #global_best
    activations:
        - identity
        - relu
        - leakyrelu
        - selu
        # - elu
        - gelu
        - sigmoid
        - tanh
    topk: 100
    output_confidence: False
    min_confidence: 0.8
    min_neurons: 1
    max_neurons: 100
    max_layers: null
    stack_hidden_layers: False
    step_neurons: 1
    local_patience: 10
    global_patience: 2
    transform_data_strategy: append_original_input
    loss_rel_tol: 0.01
    min_improvement: 0.001
    device: "cuda"

hydra:
    sweep:
        dir: outputs/${training.project_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${training.dataset}/${training.experiment_num}/
        subdir: ${training.experiment_num}
